### ISSUE TITLE
CDLC don't work

### ISSUE THREAD

**Issue by kru520** [theNizo/linux_rocksmith#10]
Debian 11
Proton 7.0-2

Thanks to your native-steam.sh script I've finally managed to play RS on linux. Working perfectly after I executed the script, followed by few commands I ran manually.

The only issue I have is with the CDLC. They don't appear in the songs list no matter what I tried.
"Cherub rock" doesn't appear in the songs list as well, although it should, because the file does exist and in the dlc folder. So I guess this is the main issue I need to fix...
The D3DX9_42.dll (from customsforge) is in the RS root folder, and the _p.psarc files are in the dlc folder, so it's probably not a silly mistake.

I suspect it has something to do with the fact RS is running externally from terminal and not directly from steam, because when I do run RS from steam, the "Cherub rock" and the rest of my CDLC are shown, but there's "no audio output device is detected" error, so it's unplayable.

Will appreciate any help ;)

**Comment by theNizo** [comment]
That's because your working directory has to be the root folder of the game (`steamapps/common/Rocksmith2014`).

If you use the terminal, `cd` into that folder first, before running the command. If you use Lutris, set it under "Game Options".

**Comment by kru520** [comment]
Turns out it was a silly mistake after all...

I didn't run `cd $STEAMLIBRARY/steamapps/common/Rocksmith2014` before 
`PIPEWIRE_LATENCY=256/48000 WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx $PROTON/bin/wine $STEAMLIBRARY/steamapps/common/Rocksmith2014/Rocksmith2014.exe`

Well, I hope it will help someone else in the future.

Edit: You've beat me to the solution :)
