### ISSUE TITLE
New Linux User (Steam Deck) - ALSA Method says ProtonTricks & WineTricks not installed

### ISSUE THREAD

**Issue by KainHighwind5** [theNizo/linux_rocksmith#11]
Thanks for providing this guide. Admittedly quite lost/overwhelmed with Linux right now (Using a Steam Deck which I believe is Arch-based). Tried the JACK to ASIO method thinking that was the best way to use the RTC but could not get that method to work past step 1.

Pivoted to the ALSA method and Konsole says ProtonTricks + WineTricks not installed. Wondering how to get those installed on the system. Appreciate any guidance you can offer or any updates to the SOP that "idiot-proof" for folks like me, thanks in advance.

**Comment by theNizo** [comment]
Hey there. AFAIK Steam Deck doesn't allow you to install packages, unless they're Flatpack. If that's still correct, the "Jack to ASIO" method doesn't work.

Usual wine has winecfg, which you can use for "quick and dirty" as well. Unfortunately, I recall Proton not having it. But you can install Lutris via flatpack and a Lutris runner from there, which has winecfg.

**Comment by KainHighwind5** [comment]
> Hey there. AFAIK Steam Deck doesn't allow you to install packages, unless they're Flatpack. If that's still correct, the "Jack to ASIO" method doesn't work.
> 
> Usual wine has winecfg, which you can use for "quick and dirty" as well. Unfortunately, I recall Proton not having it. But you can install Lutris via flatpack and a Lutris runner from there, which has winecfg.

Appreciate the follow-up! I’m admittedly unsure about not being able to install flatpak’s (still getting used to the lingo coming from 30 years of being a windows semi-power user), but what you claim makes sense at face value as to why I struggled so much following your guide.

Will give the ALSA method a second go, and will explore using Lutris. Such a painful process for those of us getting our bearings with Linux, thankful that it’s just a one-time deal. Thanks again

**Comment by theNizo** [comment]
(Packages are basically programs or software libraries.)

**Comment by BWagener** [comment]
Hi, I wanted to share I have Rocksmith with RS_ASIO working on a Steam Deck.
I followed the Arch Pipewire guide, though some things were less straightforward on the Deck.

Regarding installing packages - you can, you just have to disable the read-only mode on the root partition.

I'm happy to share the exact steps once I have the time.

It ended up working with wine-staging, proton experimental, compiling the fixed wineasio version from here https://github.com/TobiasKozel/wineasio/compare/master...BWagener:wineasio:master 
 (with slight change to get it to compile on the deck, also required some extra packages I will look up).

The result is Rocksmith on the deck with super low latency, lower than I ever achieved on my windows computer!

What I haven't gotten to work yet is outputting to the decks speakers or headphone jack.

In the end I think it would be awesome to compile all the steps into a Steam Deck specific guide/script so anyone can do it without much hassle. What do you think?

**Comment by KainHighwind5** [comment]
> Hi, I wanted to share I have Rocksmith with RS_ASIO working on a Steam Deck. I followed the Arch Pipewire guide, though some things were less straightforward on the Deck.
> 
> Regarding installing packages - you can, you just have to disable the read-only mode on the root partition.
> 
> I'm happy to share the exact steps once I have the time.
> 
> It ended up working with wine-staging, proton experimental, compiling the fixed wineasio version from here [TobiasKozel/wineasio@master...BWagener:wineasio:master](https://github.com/TobiasKozel/wineasio/compare/master...BWagener:wineasio:master) (with slight change to get it to compile on the deck, also required some extra packages I will look up).
> 
> The result is Rocksmith on the deck with super low latency, lower than I ever achieved on my windows computer!
> 
> What I haven't gotten to work yet is outputting to the decks speakers or headphone jack.
> 
> In the end I think it would be awesome to compile all the steps into a Steam Deck specific guide/script so anyone can do it without much hassle. What do you think?

I think that would be incredible, personally. I was able to get the ALSA method working but the audio delay is deal-breaking. Given mine (and likely many others) lack of experience with Linux, I’m in sore need of an idiots step-by-step guide that walks through how to get your low latency setup going.

Completely understand this can take time and would be a labor of love on your end, so no pressure, but do want to say I believe there would be a good amount of value if you were to post this guide.

thanks in advance

**Comment by theNizo** [comment]
Didn't know there was so much interest in getting this game on a handheld. But I'll take it.

**Comment by BWagener** [comment]
@KainHighwind5 thanks for the motivating words!

I've copied the guide and added the modifications necessary on the Steam Deck. 

It would be amazing if you are willing and find the time to give it a try and let me know if you get stuck. The guide is currently [here](https://github.com/BWagener/linux_rocksmith#rocksmith-on-the-steam-deck) - though it would be cool if we can eventually integrate it in this repository.

@theNizo is it okay for me to copy the guide like this? I did not want to make the effort to integrate it with your guide generation script before knowing it's solid.

Cheers

**Comment by KainHighwind5** [comment]
@BWagener will give it the old college try this weekend! I have an international business trip coming up in October, it would be nothing short of a dream come true to use the steam deck + my traveler guitar as my hotel Rocksmith machine. Will report back with my findings

**Comment by theNizo** [comment]
> @theNizo is it okay for me to copy the guide like this?

This is a Git repo. Fork all you want, as long as the credits stay ^^ BTW, I'll credit you.

I'll etheir try and find time on the weekend (including Friday afternoon) or if you understand how the guides are built, you can give me a pull request. (and I see that this process is not documented, other than the comments in the script.)

**Comment by theNizo** [comment]
@BWagner Reading your instructions, I saw that the Steam Deck seems to use pipewire, yet when you have to reinstall the JACK packages, you chose the non-pipewire version. Is there a reason behind this, or was this just by accident?

**Comment by theNizo** [comment]
@BWagener wine-mono and wine-gecko is prompted pretty often by wine. I usually have the packages `wine-mono` and `wine-gecko` installed so wine doesn't bother me all the time. I don't think you need those for Rocksmith though.

**Comment by theNizo** [comment]
Alright, the Steam Deck Guide is online in this repo and implemented in the .md generation process. I'm going to close this issue for now. If there's a mistake somewhere, go ahead and tell me ^^

**Comment by BWagener** [comment]
> @BWagener Reading your instructions, I saw that the Steam Deck seems to use pipewire, yet when you have to reinstall the JACK packages, you chose the non-pipewire version. Is there a reason behind this, or was this just by accident?

Thanks for checking my steps!

The pipewire jack packages would not work when compiling wineasio.
There were errors about a missing header like jack.h or something similar.

After some research and trial and error installing the regular jack packages was what got me past that error.
After wineasio compiled successfully I could go back to the pipewire jack packages https://github.com/BWagener/linux_rocksmith/blob/main/readme.md#L124

**Comment by BWagener** [comment]
> Alright, the Steam Deck Guide is online in this repo and implemented in the .md generation process. I'm going to close this issue for now. If there's a mistake somewhere, go ahead and tell me ^^

Awesome! Looks great, one thing that might be good to emphasize is the reinstallation of the pipewire jack packages.

I'll update the fork to point to the guide in this repo as soon as I can!
