### ISSUE TITLE
Non-descriptive title

### ISSUE THREAD

**Issue by makendorf** [theNizo/linux_rocksmith#12]
Good afternoon. I'm having problems.

Setup:
DISTRIB_ID=Manjaro Linux
DISTRIBUT_RELEASE=21.3.3
DISTRIBUT_CODENAME=Ruah
DISTRIBUT_DESCRIPTION="Manjaro Linux"

Audio card: Behringer U-Phoria UMC202
Proton 7.0.3

I tried both on ubuntu and here.
![Screenshot_20220715_163616](https://user-images.githubusercontent.com/52156615/179237361-57bdadff-9d73-4b4d-836e-105cc3361ec9.png)

I tried to do everything according to your instructions and then tried using your script. The outcome is one. Nothing works.
And it's always the same mistake. Can you tell me something?
Here is the installation log from your script: [Rocksmith_log_en.txt](https://github.com/theNizo/linux_rocksmith/files/9121401/Rocksmith_log_en.txt)
Here is the ASIO log from the game: [RS_ASIO-log.txt](https://github.com/theNizo/linux_rocksmith/files/9121406/RS_ASIO-log.txt)

**Comment by theNizo** [comment]
Also, I just noticed that the script is incompatible with Proton versions higher than 6.5. As it says, experimental, though not your fault at all.

**Comment by theNizo** [comment]
closing because of no interaction
