### ISSUE TITLE
building wineasio according to debian pipewire instructions

### ISSUE THREAD

**Issue by Juppstein** [theNizo/linux_rocksmith#17]
* **Where can the part be found?**
*  deb-pipewire-new.md
* **What is wrong with it?**
*  
> build
rm -rf build32
rm -rf build64
make 32
make 64

* **What should it be instead?**
* Did you test this with an Ubuntu 22.04 LTS box? Because I am for the life of me not able to compile wineasio on such a box

**Comment by theNizo** [comment]
I straight up took that from the [wineasio repo](https://github.com/wineasio/wineasio). Can confirm working on arch-based distros and Linux Mint.

I'll fire up a VM and test it, but I'm pretty sure it's because of missing packages.

**Comment by theNizo** [comment]
Wait a second, you're only asked to compile it yourself, if you want to use pipewire. The pipewire guides for debian-based are not finished yet.

**Comment by Juppstein** [comment]
> Wait a second, you're only asked to compile it yourself, if you want to use pipewire. The pipewire guides for debian-based are not finished yet.

Yes I know they're not finished. I just wasn't sure if you've been able to compile wineasio under 22.04 and in case you didn't try yet, I wanted to make you aware of a possible roadblock when you want to build from source on 22.04. As far as I can see it you should encounter the issue when it wants to touch jack server. This will probably conflict with files required from wine/libwine-dev due to dependencies. But since I am too much of a noob in regards to build environments I am not sure if the problem lies in wineasio or in me :D 

I've opened an issue with wineasio just to be sure https://github.com/wineasio/wineasio/issues/54

**Comment by theNizo** [comment]
> I wanted to make you aware of a possible roadblock

Ah, I see. Thanks.

**Comment by theNizo** [comment]
this sucks...

**Comment by theNizo** [comment]
Starting with a fresh os install of Ubuntu 23.10, packages I already installed for compiling:

`wine wine32:i386 make gcc gcc-multilib libjack-dev`

stuck at objbase.h not found, internet is no help...

**Comment by Knaifhogg** [comment]
I noticed the path for /usr/include/wine/ was /usr/include/wine/wine, so after changing the two include paths in the makefile I could get 64 to build. 32 still fails on linking and I can't figure out what to apt-get to make it work.

**Comment by KczBen** [comment]
I got WineASIO building on Debian Sid, both 32 and 64 bit. To get it to build, you need these packages:

- `libjack-jackd2-dev:all`, or alternatively `libjack-jackd2-dev` and `libjack-jackd2-dev:i386`. You need i386 to fix the link issue on 32 bit. It will compile the DLL, but fail to link the .so if you skip the 32 bit package.
- `wine-staging-dev` or whichever WINE branch you use. This provides `objbase.h`

From here, following the instructions on the wineasio GitHub page works for installing it. Note that the path for WINEHQ is different from the Debian packaged WINE.

For WINEHQ staging, use these paths:
32 bit libraries
`/opt/wine-staging/lib/wine/i386-unix/`
and
`/opt/wine-staging/lib/wine/i386-windows/`

64 bit libraries
`/opt/wine-staging/lib64/wine/x86_64-unix/`
and
`/opt/wine-staging/lib64/wine/x86_64-windows/`

**Comment by theNizo** [comment]
@KczBen Thank you for the input.

Since I couldn't find wine-staging and therefore installed normal wine, I installed `libwine-dev`, which should include objbase.h according to the command `dpkg -S objbase.h`. Unfortunately, I still got the same error. Maybe I could try with wine-staging.

But since you wrote that you installed wineasio via the kxrepo package and that works (can confirm), I would consider the problem resolved, since there's **a** way to get wineasio working on Debian+pipewire. I'll close this issue when the guide's updated.

**Comment by KczBen** [comment]
`wine-staging-dev` along with the other wine-dev (stable and development) packages are in the WineHQ repos. I haven't tested `libwine-dev`, as that is incompatible with the WineHQ packages. Maybe the include path is wrong for the Debian packaged dev packages, as mentioned by @Knaifhogg above?

But yes, the recommended way to install WineASIO on Debian is through the kxstudio repo, it shouldn't be necessary to build from source.

**Comment by theNizo** [comment]
We don't need to build from source and Debian guides are fixed.
