### ISSUE TITLE
Audiophile / Studio grade usb audio

### ISSUE THREAD

**Issue by stralytic** [theNizo/linux_rocksmith#24]
Just got some feedback.

I recently purchased a Behringer U-Phoria UMC404HD and wanted to use it with Rocksmith 2014, via Wineasio RS_ASIO. It took me 3 days to figure out what I was doing wrong.

First of all, this particular class of hardware is currently having some kernel support issues. I was able to get it to work with Linux-LTS 5.15.85, and with 6.0.13, but I can't get any sound in or out in any software with 6.1.1.

On the Wine side, I additionally had to:

```
WINEPREFIX=~/.local/share/Steam/steamapps/compatdata/221680/pfx wineasio-settings
```

Then in the ui, set the number of channels to match my audio device, 4-in and 4-out. I also had to set the buffer size to 256, to match what I was using in the steam launch command.

The steam launch command I was using to assist with the trouble shooting is:

```
/usr/bin/pw-jack -v -s 48000 -p 256 %command%
```

Just wanted to record my findings somewhere. Hope this helps somebody!

**Comment by stralytic** [comment]
Hey... I have another enhancement to report.

I finally figured out how to get pitch shifting to work so I don't have to retune my guitar anymore!

I'm using Tonelib-GFX (Awesome software, well worth purchasing), and using its pitch shifting.

Launch Tonelib-GFX from command line with the same `pw-jack` command as above. It's important that the buffer size for everything is the same!

Set pitch=-1, fine=0, tracking=50, direct=0 and effect=100 in Tonelib for the pitchshift plugin. In tonelib set the output to 'none'

Open `qpwgraph` before you launch Rocksmith 2014. Launch Rocksmith. While it is still on the welcome screen, disconnect rocksmith from your input device and connect it to the output of `JUCEJack`.

That should work a treat!

**Comment by theNizo** [comment]
First message here doesn't seem to need any action by me.

I'll leave the issue open in case I want to try what you mentioned in the second one.

**Comment by theNizo** [comment]
Okay, I finally tried Tonelib-GFX and wrote a page on something like this tool. I also mentioned the pw-jack debugging step now.

Actually, there is something I want to ask:

> wineasio-settings

This can't be found on my machine (compiled wineasio myself). Where did you get this from?
