### ISSUE TITLE
remove regsvr32 step (RS_ASIO got updated)

### ISSUE THREAD

**Issue by theNizo** [theNizo/linux_rocksmith#33]
Here are some instructions: https://github.com/mdias/rs_asio/blob/master/docs/linux/ubuntu_1204_lts.md

What needs to be tested:

- normal way of this guide, but without running regsvr32 and using `wineasio-rsasio` instead
- If that works, do we need to start the game from steam in the special way that is listed in the guide?

Assumuning it works, think about whether you want the now outdated steps to be collapsed with a `<details>` tag (in case someone wants to use the old version), or move the steps to the cut out ones.

**Comment by theNizo** [comment]
What I forgot to mention, I found out by the release notes of this release: https://github.com/mdias/rs_asio/releases/tag/v0.7.0

**Comment by theNizo** [comment]
Nope, doesn't work on Arch Linux with Pipewire. I'll be sticking to `regsvr32` for now.

**Comment by zurgeg** [comment]
Alright, so I've got an asciicast of how I got it working [here](https://asciinema.org/a/tOyoK95cEVo8Fuy0H7JO2SRgo). I'll see if I can make an edit to the guide based on that

**Comment by zurgeg** [comment]
Alright, made one for Arch w/ Pipewire: #37

**Comment by theNizo** [comment]
@zurgeg Thank you very much for the effort. I also didn't know about asciicinema, interesting!

Unfortunately, this is not what I'm trying to achieve.

[The latest release of RS_ASIO](https://github.com/mdias/rs_asio/releases/tag/v0.7.0) states that registering the dlls is not needed anymore. Which I cannot confirm. You registered them.

BUT this is an important aspect that I accidentally also had on my machine. Your pull request is outdated now, but I will put it in.

It's expected that the files are called `wineasio.dll` and `wineasio.dll.so`, but for future-proofing, I will use your way.

**Comment by zurgeg** [comment]
Ahh, right. I think you should be able to copy the files manually (wineasio-register does that for you), although the benefit of doing that over just registering with wineasio's tools is questionable imo

**Comment by theNizo** [comment]
Not gonna bother anymore.
