### ISSUE TITLE
Wrong copy destination folder

### ISSUE THREAD

**Issue by web-kurl** [theNizo/linux_rocksmith#38]
When coping wine asio to proton folder, your guide on arch with pipewire says:

cp "$PROTON/lib64/wine/x86_64-windows/wineasio64.dll" "$PROTON/lib/wine/x86_64-windows/wineasio.dll"
cp "$PROTON/lib64/wine/x86_64-unix/wineasio64.dll.so" "$PROTON/lib/wine/x86_64-unix/wineasio.dll.so"

The destination folder doesn't exist, I think is wrong,
May this is the correct command:

cp "$PROTON/lib64/wine/x86_64-windows/wineasio64.dll" "$PROTON/lib64/wine/x86_64-windows/wineasio.dll"
cp "$PROTON/lib64/wine/x86_64-unix/wineasio64.dll.so" "$PROTON/lib64/wine/x86_64-unix/wineasio.dll.so"

*Similar that you have done above, coping the same file with different name

First of my, my very first post here. Second, THANK YOU. 
I already could make Rocksmith run on arch linux, but had to format and I'm doing it again. 
I'm struggling really hard on setting $STEAM path because it has a space on the path, I tried to use the path on single ' ' and double " " quotes , substitute the space to ?, *, /040, \ but nothing worked, spend more than a week trying to figure out with no success, I had to drop it  and use the whole path.

**Comment by theNizo** [comment]
Fixed, thank you.
