### ISSUE TITLE
VBASIOTest32 doesn't find devices, but VBASIOTest64 does

### ISSUE THREAD

**Issue by cyprienruffino** [theNizo/linux_rocksmith#39]
Hi, awesome guide, thanks so much, I finally got Rocksmith working without latency!

* **Where can the part be found?**
* Arch with Pipewire, under the wineasio section. Maybe it's the same for the other guides, but I only tried this one.
```
WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx $PROTON/bin/wine /path/to/VBASIOTest32.exe
```

* **What is wrong with it?**
*  To check if wineasio has been installed correctly for the prefix, you recommend using VBASIOTest32, which (for me at least) didn't find any devices, but VBASIOTest64 worked. I started the tutorial from scratch twice because i couldn't find my devices and thought I did something wrong.

* **What should it be instead?**
```
WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx $PROTON/bin/wine /path/to/VBASIOTest64.exe
```

Thanks again for the awesome work :)

**Comment by theNizo** [comment]
Hi, thanks for the feedback.

Rocksmith is a 32 bit application. Because of that, I used the 32 bit version of the test.

What confuses me is that Rocksmith apparently works for you, but the test doesn't...

**Comment by cyprienruffino** [comment]
I can provide you with more data if you want.
I am surprised too about this, but I tested it again and I can confirm that VBASIOTest32 does not find any audio devices, whereas VBASIOTest32 indeed finds wineasio.

**Comment by theNizo** [comment]
This issue is quite old.

Is it worth revisiting, or should we close it?

**Comment by cyprienruffino** [comment]
I don't think so, no. Thank you for your time
