### ISSUE TITLE
Can't seem to generate proton launch script.

### ISSUE THREAD

**Issue by NaMLiM** [theNizo/linux_rocksmith#44]
* Which distro do you use?
> EndeavourOS
* Which Proton or wine version do you use?
> Proton-GE9.1
* Do you use pipewire?
> Yes
* What appears to be the problem? (Describe it as best as you can)
> i can't seem to generate the proton launch script on /tmp. i already put `PROTON_DUMP_DEBUG_COMMANDS` on launch options.
* Did you notice any other unexpected behavior?
> nope
* What did you try already?
> i tried the `LD_PRELOAD` method and it works. wineasio seems to be running, the problem is when i tinker with patchbay it crashes the game (like the guide said, has high probability of crashes).
* Did you do any of the steps differently or leave them out?
> i believe i have followed all the steps

**Comment by theNizo** [comment]
Try Proton 8.

(Rocksmith has been working fine since at least Proton 3 anyway.)

---

There seems be a change since Proton 9. This doesn't work on official Proton 9, Proton Experimental and apparently Proton-GE anymore.

I'm currently reworking the non-arch guides and will make one big update.

(I'll close the issue after changing the guide.)

**Comment by theNizo** [comment]
Yes, flag is available in [Proton 8 README](https://github.com/ValveSoftware/Proton/blob/proton_8.0/README.md), but not in [Proton 9 README](https://github.com/ValveSoftware/Proton/blob/proton_9.0/README.md).

Relevant Issue: https://github.com/ValveSoftware/Proton/issues/7575

**Comment by NaMLiM** [comment]
> Try Proton 8.
thank you it work, now i can play rocksmith on linux using my audio interface.

**Comment by theNizo** [comment]
Okay, I got it working with Proton 9. Basically, I started Rocksmith with the launch options `PRESSURE_VESSEL_SHELL=instead %command%`. I then ran

```
# choose your filenames
echo $@ > proton9-launch
echo $(env) > environment
```

I then put a bunch of seemingly useful environment variables in front, with the PIPEWIRE_LATENCY flag and it worked.

Now I need to figure out which environment variables I need.

**Comment by theNizo** [comment]
Absolute minimum needed variables (only posting the names, pick them out yourself):

```
SteamAppId
STEAM_COMPAT_CLIENT_INSTALL_PATH
STEAM_COMPAT_DATA_PATH
```

potentially useful ones

```
SteamClientLaunch=1
PWD <-- Nope, can't figure out what for
container=pressure-vessel
SteamClientLaunch=1
SteamOverlayGameId=221680 <-- Can't see the overlay either way
STEAM_COMPAT_PROTON
STEAM_ZENITY
SteamEnv
SteamVirtualGamepadInfo_Proton <-- gamepad translation, probably
```

Please keep in mind that this was just done by trial and error.
