### ISSUE TITLE
When launching rocksmith through steam wineasio doesn't work but when launching in terminal it works fine

### ISSUE THREAD

**Issue by Skyler69420** [theNizo/linux_rocksmith#51]
* Which distro do you use? 
Manjaro
* Which Proton or wine version do you use? 
*Experimental and tried 9.0-2
* Do you use pipewire? 
Yes
* What appears to be the problem? (Describe it as best as you can)
When launching the game via Steam rocksmith hangs for a second as it tries to load wineasio. 

WineASIO log:
```
`0.153 [INFO]  Creating AsioSharedHost - dll: C:\windows\system32\wineasio.dll
6.211 [ERROR]  ASIO Error: WineASIO does not return error messages

6.211 [INFO]  Destroying AsioSharedHost - dll: C:\windows\system32\wineasio.dll
6.211 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.`
```

However 15 seconds later it says no output device can be found and launches the game without sound. However when I launch the game in terminal with the old workaround command you mentioned in the guide it works fine however it doesn't detect Steam is open.

I'm unable to use the WineASIO debug terminal command since launching in terminal works fine

* Did you notice any other unexpected behavior?
Nothing that wasn't mentioned
* What did you try already?
Reinstalled WineASIO a bunch of times. I also tried the tool you suggested to see if everything works and it does. I even installed the windows version of reaper into Rocksmiths prefix and that also worked fine
 
* Did you do any of the steps differently or leave them out?
No

I'd prefer to launch with Steam for convenience compared to terminal and so it can track my hours and use achievements

**Comment by theNizo** [comment]
> WineASIO log:

AFAK, it does that multiple times, right?

---

The description "It doesn't work when launching from Steam" is pretty generic. I assume you have read [this part in the guide](https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup/arch-pipewire.md#starting-the-game):

> If we start the game from the button that says "Play" in Steam, the game can't connect to wineasio (you won't have sound and will get an error message). This is an issue with Steam and pipewire-jack.

and if you start it from Steam, I assume you're trying the LD_PRELOAD method. Is that correct?

**Comment by Skyler69420** [comment]
I'll be honest it turns out that I jumped the gun and didn't read the full guide, my bad. The LD_PRELOAD did not work for me. It would not launch the game and would crash straight away. However the second method works flawlessly

**Comment by theNizo** [comment]
Okay, got it.

> The LD_PRELOAD did not work for me

Good to know, this way currently doesn't work on my system either, so I'll put a warning there for the Arch-based guides.
