### ISSUE TITLE
wine: chdir to /steamapps/compatdata/221680/pfx : No such file or directory

### ISSUE THREAD

**Issue by Gribovoy29** [theNizo/linux_rocksmith#52]
* Which distro do you use?
* Which Proton or wine version do you use?
* Do you use pipewire?
* What appears to be the problem? (Describe it as best as you can)
* Did you notice any other unexpected behavior?
* What did you try already?
* Did you do any of the steps differently or leave them out?

Hello. I stumbled upon an error when running the line :
env WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx ./wineasio-register

The console outputs :
wine: chdir to /steamapps/compatdata/221680/pfx : No such file or directory

But the folder exists.

I am using Arch with Pipewire. I did all of the steps before and haven't had any errors.

Thanks in advance

**Comment by theNizo** [comment]
The environment variable $STEAMLIBRARY isn't set.

**Comment by Gribovoy29** [comment]
Could you please tell me how do I do that?

**Comment by Gribovoy29** [comment]
I have found a guide on reddit, but still doesn't work for me.

**Comment by theNizo** [comment]
See the [common paths section](https://github.com/theNizo/linux_rocksmith?tab=readme-ov-file#common-paths), where there's more, detailed information.

To repeat myself:

For the default Steam Library it would be

```
STEAMLIBRARY=$HOME/.steam/steam/
```

Setting it this way will only be temporary, meaning it only applies to the terminal window in which you set it.
