### ISSUE TITLE
Proton 9 on Garuda has /files instead of /dist

### ISSUE THREAD

**Issue by joaociocca** [theNizo/linux_rocksmith#56]
* **Where can the part be found?**

https://github.com/theNizo/linux_rocksmith/blob/996312836c0c2fe96745097711c8bc2bed889209/README.md#L31-L32

* **What is wrong with it?**

Dunno about other distros, but for Garuda with Proton 9, the path ends in `/files` instead of `/dist`! There is no "dist" folder there.

```
2024-08-21 00:54:11  find /dev/home/.steam/steam/steamapps/common/ -name Proton*
/dev/home/.steam/steam/steamapps/common/Proton 9.0 (Beta)
                                                                                                                                             
2024-08-21 00:54:27  find /dev/home/.steam/steam/steamapps/common/Proton\ 9.0\ \(Beta\) -name dist
                                                                                                                                             
2024-08-21 00:54:32  find /dev/home/.steam/steam/steamapps/common/Proton\ 9.0\ \(Beta\) -name files
/dev/home/.steam/steam/steamapps/common/Proton 9.0 (Beta)/files
                                                                                                                                             
2024-08-21 00:54:48  ll /dev/home/.steam/steam/steamapps/common/Proton\ 9.0\ \(Beta\)/files
drwxr-xr-x  - johnny  8 ago 16:43  bin
drwxr-xr-x  - johnny  8 ago 16:43  lib
drwxr-xr-x  - johnny  8 ago 16:43  lib64
drwxr-xr-x  - johnny  8 ago 16:43  share
.rw-r--r-- 18 johnny  8 ago 16:43  steampipe_fixups_mtime
```

For me, this was what lead me to RS not finding the `wineasio.dll` file on that other comment (https://github.com/theNizo/linux_rocksmith/discussions/55#discussioncomment-10402109)

* **What should it be instead?**

Let user know they need to check the Proton folder for a `/dist` or a `/files` folder, and that one should be mapped as `$PROTON`?

**Comment by theNizo** [comment]
This is not Garuda-specific and it IS listed under the sectian "common paths".

> Other Proton (GE, Valve Experimental/Beta, etc.): It's located in the default Steam Library under `compatibilitytools.d/Proton-#.##-GE-#/files`

Well, it is listed with GE as example, but you got the point.

**Comment by joaociocca** [comment]
> sectian "common paths".

oh. damn, I was sure I read it over 10 times and couldn't find that ._.

**Comment by theNizo** [comment]
Since I think "you get the point" isn't such a good response, I edited the section regardless after thinking about it. Hopefully this is better.

**Comment by joaociocca** [comment]
you're a better person than most people I know! This makes me feel like my input was useful in some way =) thanks!
