### ISSUE TITLE
I  get stuck following the guide at "WATCH OUT FOR VARIABLES"  step 

### ISSUE THREAD

**Issue by zoobporsor** [theNizo/linux_rocksmith#58]
* Which distro do you use? Arch Linux
* Which Proton or wine version do you use? Experimental
* Do you use pipewire? Yes 
* What appears to be the problem? (Describe it as best as you can)

I'm following the guide, https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup/arch-pipewire.md

I get stuck at the step 

```
"To make Proton use wineasio, we need to copy these files into the appropriate locations:
# !!! WATCH OUT FOR VARIABLES !!!
cp /usr/lib32/wine/i386-unix/wineasio32.dll.so "$PROTON/lib/wine/i386-unix/wineasio32.dll.so"
cp /usr/lib/wine/x86_64-unix/wineasio64.dll.so "$PROTON/lib64/wine/x86_64-unix/wineasio64.dll.so"
cp /usr/lib32/wine/i386-windows/wineasio32.dll "$PROTON/lib/wine/i386-windows/wineasio32.dll"
cp /usr/lib/wine/x86_64-windows/wineasio64.dll "$PROTON/lib64/wine/x86_64-windows/wineasio64.dll""
```
```
The commands dont work

[zeebpc@arch wineasio-1.2.0]$ cp /usr/lib32/wine/i386-unix/wineasio32.dll.so "$PROTON/lib/wine/i386-unix/wineasio32.dll.so"
cp: cannot create regular file '/lib/wine/i386-unix/wineasio32.dll.so': No such file or directory
```

What does "WATCH OUT FOR VARIABLES" mean? What should I do?

**Comment by zoobporsor** [comment]
I managed to manually use a GUI to track down the files and copy them over, but I dont know how I was supposd to get the commands to work
Now im stuck at another step

To register wineasio (so that it can be used in the prefix), run the wineasio-register script that comes in the wineasio zip and set the WINEPREFIX to Rocksmiths.

env WINEPREFIX=$STEAMLIBRARY/steamapps/compatdata/221680/pfx ./wineasio-register

Where do I put this command?
sorry for basic noob mistakes I am trying to learn

**Comment by theNizo** [comment]
> What does "WATCH OUT FOR VARIABLES" mean?

It's a reminder that you should set the environment variables as mentioned in the [prerequisites](https://github.com/thenizo/linux_rocksmith/?tab=readme-ov-file#prerequisites). Otherwise, the paths won't be recognized correctly.

Also see #52

**Comment by theNizo** [comment]
Sorry, didn't read till the end.

> Also, earlier in the guide to test if wineasio works, the command also does not work for me.

Actually no idea, tbh.

The command just searches for the files and reports where they are IF you placed them. It's meant to quickly see if they are in the correct spots. You could also check that manually.

> Managed to get it all working, but I usually have to start the game multiple times for it to start working [...]

That's new behavior to me.

I would guess that it freezes in the first few seconds, or rather, even in the first second. Can you please try the following, for further analysis:

- As soon as you see the Rocksmith Window pop up, alt-tab away, wait a few seconds, the focus again
- look at the patchbay and see if something weird happens. (Although sudden changes there would lead to the game crashing)
- does it behave different if you run the script from terminal?

**Comment by zoobporsor** [comment]
thanks for replying so soon 

I suggest to edit the guide and specify that proper variables need to be set to run the commands  given, because by default I dont have anything set for $PROTON and $STEAMLIBRARY (echo $PROTON to test for example, its blank for me)  
so either direct them to plug in the paths manually, or direct them to set the variables up first. 

Another person had the same confusion as me 
https://www.reddit.com/r/rocksmith/comments/18dh9bo/some_issues_i_ran_into_running_rs_with_rs_asio_on/

I will keep testing the crashes, it seems like so far it has run 100% of time thru terminal, and through steam shortcut it crashes frequently

However I have since restarted steam and I havnt noticed a crash, so maybe its just a fluke. Thank you

**Comment by theNizo** [comment]
> I wonder why my Arch system doesnt have any default paths for $PROTON and $STEAMLIBRARY, it seems like its usually setup automatically

Those are made up by me. I use them in the guide so that readers can just copy-paste them.

> Maybe preface this page with

Agreed.

**Comment by theNizo** [comment]
Done.

f0ebd54
e6c4ee5
e785b14
4718ac6

Let me know if I missed something.
