### ISSUE TITLE
Real tone cable ingame setting uses microphone

### ISSUE THREAD

**Issue by FourH3ad** [theNizo/linux_rocksmith#61]
* Which distro do you use?
Arch
* Which Proton or wine version do you use?
Proton-8.05
* Do you use pipewire?
Yes
* What appears to be the problem? (Describe it as best as you can)

Playing using a Focusrite Scarlett solo 2nd gen with guitar and headset plugged in.
Everything audio input and output wise goes through the Focusrite.
Nothing else is physically connected (excluding the hdmi audio from monitor this is disabled in system settings).

When selecting real tone cable in rocksmith it uses my mic.
When selecting Asio in 2 nothing is sent to rocksmith (or so it seems).

When setting direct monitor on i do hear my guitar, so the audio input works.

All is connected well in qpwgraph

When simply using the real tone cable the same thing happens.

Selecting the mic or real tone cable as default in system settings crashes rocksmith when launching

* Did you notice any other unexpected behavior?
It worked yesterday and nothing changed :(

* What did you try already?
Reboot
Limited devices to 3
Set sample rate with the command listed in troubleshooting.

* Did you do any of the steps differently or leave them out?
When launching the game using the script i set in the path instead of using $steamlibrary

Screenshots:
Jack
![2024-11-06_18-09](https://github.com/user-attachments/assets/7cf039b7-8b58-421e-8f1a-0bc40afdab6e)
System settings:
![2024-11-06_18-10](https://github.com/user-attachments/assets/a36afab1-b591-4539-ae6e-a3792e1b1a11)

LOG:
[RS_ASIO-log.txt](https://github.com/user-attachments/files/17651056/RS_ASIO-log.txt)

**Comment by theNizo** [comment]
I have a few questions.

- The Focusrite Scarlett Solo can do 2 inputs?
- Can I see your RS_ASIO.ini? The channels are probably set up wrong. (You can also have a look at [this](https://github.com/theNizo/linux_rocksmith/blob/pipewire-plus-jack/guides/setup-rs-asio.md))
- In pavucontrol -> configuration, have you set the Scarlett to "Pro Audio"? If so, don't do that when using with Rocksmith. It causes headaches in my experience.

**Comment by FourH3ad** [comment]
Hey Nizo,

- The Focusrite Scarlett Solo can do 2 inputs?

It has an xlr mic input, a 3/4 guitar input and a headphone input.

-     Can I see your RS_ASIO.ini?

Certainly (had to change to txt to upload)
[RS_ASIO.txt](https://github.com/user-attachments/files/17651386/RS_ASIO.txt)
    
-     In pavucontrol -> configuration, have you set the Scarlett to "Pro Audio"? If so, don't do that when using with Rocksmith. It causes headaches in my experience.

It's set to "default"
Setting it to "Direct Scarlett Solo USB also causes a crash upon starting

![2024-11-06_19-19](https://github.com/user-attachments/assets/d2d6ab4b-5198-44f8-9eb5-7b50a05f267e)

**Comment by theNizo** [comment]
Okay.

RS_ASIO config looks good.

It took a second, because based on the screenshot I'm not quite sure where you navigated to and your options look different than mine.

<details><summary>Mine look like this</summary>

![Screenshot_2024-11-06T19-36-03](https://github.com/user-attachments/assets/b3272ece-d08b-449c-9ff6-ef8bd259c52f)

![Screenshot_2024-11-06T19-36-21](https://github.com/user-attachments/assets/92dfad4b-1c9b-4ae9-9a07-5681b43a5f0d)

</details>

RS_ASIO is simulating 2 RealToneCables. I suppose you need to select the correct one ingame.

The following steps should fix it:

Start Rocksmith and select your proflie. You should be at this screen now:

![Screenshot_2024-11-06T19-44-38](https://github.com/user-attachments/assets/203464eb-4cd9-481e-a42b-5fa8df0f1b16)

1. Press Ctrl to open input settings.
2. Select Microphone
3. Go into "Available inputs" below
4. Select the SECOND RealToneCable.
5. You should hear sound now.

**Comment by FourH3ad** [comment]
Maybe this is the issue, I only have one realtonecable.
This one picks up the mic.
The asio 2 picks up nothing.

But looking at qpwgraph i only have 2 inputs the mic and inst/line.
<details><summary>Screenshot</summary>
<p>

![2024-11-07_07-58](https://github.com/user-attachments/assets/75e0e8a1-2432-44d6-8db5-dc80003f62db)

</p>
</details> 

I've also done a little testing with the realtonecable plugged in.
Even then it still only shows 1 realtone and 1 asio input.

<details><summary>Screenshot</summary>
<p>

![2024-11-07_08-11](https://github.com/user-attachments/assets/8aeb1fc1-5a82-42dc-b5b6-12257ba63a4c)

</p>
</details>

**Comment by theNizo** [comment]
Wait a second, your RS_ASIO.ini has a typo in line 30 (last character). That could be why it doesn't show up.

And that's probably why, according to the first message here, you can't hear that input.

---

> Maybe this is the issue, I only have one realtonecable.

Apparently I confused you a bit with this.

The devices you see ingame are SIMULATED by RS_ASIO. The names have absolutely nothing to do with what's actually plugged in.

Asio.Input.0 will always be the first "RealToneCable" ingame
Asio.Input.1 will always be the second "RealToneCable" ingame
Asio.Input.Mic will always be "{ASIO IN 2}" ingame.

**Comment by FourH3ad** [comment]
Bruh it was the typo ain't no way XD

It now indeed shows 2 realtonecables (i did understand what u meant i also meant inside the game).
One for the focusrite and one for the actual cable.

Both work with sound being played if switched to said option.

Thanks for your help and the amazing work with the guide!

I've updated my protondb entry with a link to your guide so hopefully more people will find it.
It's still pending but should soon be updated.
