### ISSUE TITLE
Volume changes crash rocksmith

### ISSUE THREAD

**Issue by sbeuh34** [theNizo/linux_rocksmith#63]
Which distro do you use?
 - Steam OS - steam deck

Which Proton or wine version do you use?
 - Proton Experimental

Do you use pipewire?
 - Yes

did you choose native JACK or pipewire-jack?
 - pipewire-jack

What appears to be the problem? (Describe it as best as you can)
 - Any OS volume change from the steam deck volume buttons or from external soundcard buttons (tried with and without external soundcard) crash the game instantly

Did you notice any other unexpected behavior?
 - No

What did you try already?
 - Tried to play with values in both Rocksmith.ini (exclusive mode) and RSAsio.ini (volume control values) without any success

Did you do any of the steps differently or leave them out?
 - I followed the steps for steam deck pipewire-jack version of this guide with both proton 9 beta (which didn't worked) and Proton experimental (which worked). Nothing more fancy, it worked kinda straight forward.
 
 Thank you guys for the amazing work of documentation and guidance!

**Comment by theNizo** [comment]
Could you try and test this further/tell me more? (Haven't read about this behavior before.)

* Is that in desktop mode, or the big picture mode?
* Can you change it using a command? (I'll post the one I used in my tiling wm when I'm on my PC again) - come to think of it, opening a terminal in Big Picture might not be so easy - but isn't there a Decky Loader plugin to run commands?
* Can you change it in pavucontrol?

(Just for clarity, "can you change it" means "does the game crash when you do it")

The obvious workaround would be to use something with a volume knob. But even if that's feasible for you, that's still annoying and I can tell it bothers you either way because you wrote this issue.

**Comment by sbeuh34** [comment]
Yes, I also have a soundcard with a knob which would obviously work because it doesn't change the deck volume. But my goal is before and foremost to be able to play and practice on the go with the steamdeck. It works really well with Jack and Pipewire, the latency is incredibly small and the sound isn't distorted like on my previous attempts on the steamdeck. 

Only issue on my side which make it playable but a bit boring to play is that crash when you need to change the volume, which can happen quite often if you're playing CDLC as the guitar volume is sometimes too high depending the sound effect of the song.

To be honnest it doesn't bother me that much, and I am already able to enjoy it! But I know that if I'm facing that issue, maybe other can experiment it as well, so well it will maybe help other users on the community.

I'm not on Big picture mode as it crashes every time on big picture mode. And I still have to select my RS tone cable as the default input on steam deck launch so, moving in desktop mode every time I want to play RS.

I did some test with "amixer" command and I figured out that when RS doesn't have the focus, it doesn't crash at all. Basically it made me think about an exclusivity issue so I disabled exclusive mode and tested again. Of course I got the Message from RS-Asio letting me know that I didn't had exclusive mode on followed by the rocksmith popup (no output device available) but I was able to change the volume.

Maybe the issue is as dumb as the steam deck shows a little volume notification window and make a small sound when you change the volume and rocksmith which is then in exclusive mode doesn't like the fact that something else is trying to make a sound and just crash.

I'm gonna try to test some other things.

Thanks for your reply!

**Comment by sbeuh34** [comment]
Just tried something. I went into the SteamOs settings from desktop mode, in the audio section there is a setting called: 
**Play audio feedback for changes to Audio Volume** which is checked and is responsible of that little tick sound on volume change. I disabled it and guess what. No crash at all anymore. Maybe that could be something which needs to be added on the guide or on the troubleshooting section!

Maybe something else would be doable to allow Rocksmith to run without having to disable that setting but not sure what. I'll do some research on changing SteamOS settings from command line and maybe that could be added to the startup script to disable it on RS launch and re-enable it after Rocksmith has been shutdown.

**Comment by sbeuh34** [comment]
#Definitely worth noting and I might put this inside the Steam Deck guide instead, just below the start script links
I guess that would definitely help other steam deck users! Thanks

I searched for an option to change values of plasma settings from terminal but didn't found one. Not having the volume change notification sound isn't really annoying from my POV

**Comment by theNizo** [comment]
Done 0456b69
