### ISSUE TITLE
Linux Mint 22 - no audio output and calibration fail

### ISSUE THREAD

**Issue by DerekJarvis** [theNizo/linux_rocksmith#64]
* Which distro do you use?
Linux Mint 22

* Which Proton or wine version do you use?
wine 9.0

* Do you use pipewire?
Yes

* did you choose native JACK or pipewire-jack?
I'm not sure

* What appears to be the problem? (Describe it as best as you can)
I can't get any audio output, and when I'm trying to calibrate, the second time it asks me to mute the strings the input seems to go crazy and cause spikes even though the strings have been muted. This puts rocksmith into a weird loop where it keeps asking to try again and reset the settings. I think it's incorrectly adjusting the gain, and I have no way to see or control it.

* Did you notice any other unexpected behavior?
No

* What did you try already?
I've tried using the steps in the guide, as well as resetting my prefix and specifically setting it as a 32bit prefix. 

* Did you do any of the steps differently or leave them out?
I didn't try to use proton because I could never get it to work.

I'd happily pay for a live debugging session to get this working. I've spent way to much time on it already! But this guide is really great and is the only reason I've been able to come this far.

**Comment by theNizo** [comment]
> * did you choose native JACK or pipewire-jack?
> I'm not sure

On which link did you click?

![2306bc97-9d15-40ad-b65a-1d2f74dcbb9d](https://github.com/user-attachments/assets/b749f022-b5de-46b3-8de3-ca3c9ad21a85)

And what's the output of `apt list --installed | grep jack`?

> I didn't try to use proton because I could never get it to work.

Judging by that, there's a lot of things you could be doing different, with no way for me to tell what you did.

> live debugging session

Do you have time somewhere in the next 8 hours?

**Comment by theNizo** [comment]
> mine has the wine bin under a "files" subdirectory

[That's expected](https://github.com/theNizo/linux_rocksmith/?tab=readme-ov-file#common-paths), excerpt:

* Valve Beta/Experimental: (Example with Experimental) `/path/to/steamapps/common/Proton\ -\ Experimental/files`

---

> I can't get any audio output

The game doesn't give you any sound, or you can't hear your guitar ingame?

If it's the first one, it might need a little bit debugging and more info. If it's the second one, you're pretty far already:

* Look at ["Set up RS_ASIO"](https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup-rs-asio.md)
* Compare it with the patchbay
* Set volume of your input to 100% in pavucontrol
* If you use an audio interface, set your gain properly.

---

I'm not sure if I'm ready to do this during the week. Tomorrow might work.
You can write me at `d4d74f18-407f-409c-81eb-82ecdc30ab8f@anonaddy.me` (throwaway, will be terminated afterwards.)

**Comment by DerekJarvis** [comment]
I did a bit more digging, and finally got it working (mostly), so I thought I'd share my notes here in case it helps someone else - and in case you can tell me other ways I can improve this setup.

## JACK Server issues
When running VBASIO, or Rocksmith, I would get some errors about not being able to get a device for playback:
```
audio_reservation_init
Acquire audio card Audio1
creating alsa driver ... hw:Adapter|hw:Adapter|1024|2|48000|0|0|nomon|swmeter|-|32bit
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
```

I was launching my jack server with this command: `pw-jack qjackctl`, doing my configuration there and pressing start. I noticed that the settings didn't seem to persist, and it seems like whatever that was doing was not able to be grabbed by Rocksmith.

I found another forum talking about launching jack manually with `jackd -d alsa -d pipewire -p 256 -r 48000`

When doing this, suddenly I can hear the output from VBASIO, and both input and output in Rocksmith work!

## Proton Issues
As mentioned, when trying to run proton experimental I got errors - specifically it was unable to find any of the 3D drivers:
```
0024:err:module:import_dll Library libvkd3d-1.dll (which is needed by L"C:\\windows\\system32\\wined3d.dll") not found
0024:err:module:import_dll Library libvkd3d-shader-1.dll (which is needed by L"C:\\windows\\system32\\wined3d.dll") not found
0024:err:module:import_dll Library wined3d.dll (which is needed by L"C:\\windows\\system32\\d3dcompiler_47.dll") not found
0024:err:module:import_dll Library d3dcompiler_47.dll (which is needed by L"C:\\windows\\system32\\d3dx9_42.dll") not found
0024:err:module:import_dll Library d3dx9_42.dll (which is needed by L"Z:\\...\\Rocksmith2014.exe") not found
MESA-INTEL: warning: cannot initialize blitter engine
005c:err:xrandr:xrandr14_get_adapters Failed to get adapters
```

Going back to regular wine with a special prefix directory for Rocksmith I was able to get things working fine.

**Comment by DerekJarvis** [comment]
Oh, and one last thing - I never see the rocksmith adapter in the patchbay graph as shown in the docs, and when I was using the `pw-jack qjackctl` command the cable input would disappear from the graph. With the new jack command I can still see the cable while rocksmith is playing - but still no panel with all the connectors. I found that changing my default system input to the cable allows Rocksmith to capture the cable I'm not using it for multiplayer so that's OK for me, even if it's a slightly inconvenient extra step.

**Comment by theNizo** [comment]
> Why are you using the pw-jack command in the first place?

And why did you not list it in steps done different?

**Comment by DerekJarvis** [comment]
1 - On using pw-jack qjackctl
This is my first time using qjackctl and some guide I found mentioned this was the command to use. Did I miss a section in the guide where it explicitly tells us how to launch the JACK server?  I didn't see it, and so I figured it's something everyone knew how to do and looked for a guide for it. That's also why I didn't list it as a deviation, because I didn't see anywhere we were told how to do it - so I didn't consider my found approach a deviation.

2 - On Proton, understood - but I'll leave it be. It's working fine with wine.

3 - About the "patchbay graph as shown in the docs", I'm referring to this link you shared: https://github.com/theNizo/linux_rocksmith/blob/main/guides/setup-rs-asio.md

And specifically this part of the image: 
![image](https://github.com/user-attachments/assets/1028f957-3879-4ec6-828d-d8099ae3bef1)

I've never seen this in the node in qjackctl in order to try to draw any connections between them. I've only seen this one:
![image](https://github.com/user-attachments/assets/49c6816d-74c9-40e0-a5e7-7e6a7b3d6bb1)


Verification: provided deepness mocker

**Comment by theNizo** [comment]
> On using pw-jack qjackctl

Not necessary. `jackd2` needs to be started manually. `pipewire-jack` doesn't have to be, it's already running and available.

> And specifically this part of the image:

OH, okay. I was thinking about the hardware accessory, not the Rocksmith instance shown in the patchbay. This could have meant

* You have a RealToneCable, but it doesn't show up
* You don't have one, but expected to see it
* Meaning something else than the cable

Oh, wait, that's not exactly 5 things. Well, I overestimated it, my apologies.

Seeing from the email that you don't need any further help, I'm gonna close this issue now, complaints about closure to be filed here.

**Comment by theNizo** [comment]
Apparently, I can not send you another email back. Bad choice on my side. The outcome is the same, you don't have to pay me, and due to privacy concerns, I would have given you no way to pay me anyway, that's alright. ^^
