### ISSUE TITLE
On arch /w wineasio doesn't seem to work

### ISSUE THREAD

**Issue by ciolansteen** [theNizo/linux_rocksmith#9]
OS - Arch Linux
I remember that some time ago I managed to launch RS and make it work with RS-ASIO but only from the command line. Not sure where i wrote about it back then. Anyways, using proton v7 and wineasio compiled from github, spits out this. Didn't try the aur package because it does the same thing (pulls the repo, compiles and copies the files in lib dirs).

0.000 [INFO]   - Wrapper DLL loaded (v0.5.7)
0.000 [INFO]  PatchOriginalCode
.......................
0.335 [INFO]  AsioHelpers::FindDrivers
0.339 [INFO]    WineASIO
0.339 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - output requesting ASIO driver: WineASIO
0.339 [INFO]  Creating AsioSharedHost - dll: wineasio.dll
0.340 [INFO]  Destroying AsioSharedHost - dll: wineasio.dll
0.340 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.340 [INFO]  RSAsioDeviceEnum::UpdateAvailableDevices - input[0] requesting ASIO driver: WineASIO
0.340 [INFO]  Creating AsioSharedHost - dll: wineasio.dll
0.340 [INFO]  Destroying AsioSharedHost - dll: wineasio.dll
0.340 [ERROR]  RSAsioDeviceEnum::UpdateAvailableDevices - failed.
0.340 [INFO]  DebugDeviceEnum::UpdateAvailableDevices - 0 render devices, 0 capture devices
 .......................

**Comment by ciolansteen** [comment]
I do. my default pipewire setting is 48KHz / 128. I tried both pipewire conf and PIPEWIRE_LATENCY var - same result

**Comment by theNizo** [comment]
Having a closer look at it, RS_ASIO tries to connect to wineasio two times before giving up and saying 0 input and output devices. This is usual behavior when something isn't set up correctly and you should be getting this error message:

![image](https://user-images.githubusercontent.com/46491912/161832608-b333a1ae-80f7-4f0b-82d0-d7e87b9f4e9f.png)

(You didn't tell me you got it, which would be weird. I'll just assume that you got it for now.)

---

the game can find _something_, but it doesn't seem to be set up correctly. So let's go through some steps:

Could you please go inside the dist/files folder in the Proton version you use, run these commands from there (should output 8 paths, ignore the errors inbetween) and give me the output?

	find lib -name "wineasio.dll"
	find lib -name "wineasio.dll.so"
	find lib64 -name "wineasio.dll"
	find lib64 -name "wineasio.dll.so"
	find /usr/lib/ -name "wineasio.dll"
	find /usr/lib/ -name "wineasio.dll.so"
	find /usr/lib32/ -name "wineasio.dll"
	find /usr/lib32/ -name "wineasio.dll.so"

Did you patch the prefix and did it say that it was successful?

If we're still not any further in finding the issue, I would go to these questions:

* Did you use the correct prefix?
* Did you use the correct Proton version?
* are you in the audio and realtime groups?

**Comment by ciolansteen** [comment]
Yep, all is correct. Tried with both tobi's and falkTX forks. I might be missing smth though... I tried using wineasio with amplitube4 from the same container (prefix) last night. The problem seems to be related to the 32bit version of the library. The 64bit one just works while the other doesn't.  I remember this used to be a issue with wineasio in the past too. Maybe a regression coming from the way jack is implemented in pipewire? Chances are i'm far off the track on this thought, but the behaviour seems somehow similar.

I don't have much experience with troubleshooting wine nor much time to dig into this right now. I will try more over the weekend and come back with the results. 

Oh, and about pavucontrol thing.... coorect me if i'm wrong, but i think what you are trying to achieve with that is limiting wineasio i/o detection to one input + one output? Did you try setting that up in the ./pfx/../user.reg? Running settings.py (from the wineasio repo) in that prefix will set that registry entry up for you. All you need after that is edit it to fit your needs.

**Comment by theNizo** [comment]
> The problem seems to be related to the 32bit version of the library. The 64bit one just works while the other doesn't.

Wait a second, do you have `lib32-pipewire-jack` installed? Without it I wasn't able to compile 32bit wineasio (I just recently found out).

> I don't have much experience with troubleshooting wine

Yeah, me neither XD

> Oh, and about pavucontrol thing.... corect me if i'm wrong, but i think what you are trying to achieve with that is limiting wineasio i/o detection to one input + one output?

Yup. I can have a look at what you meant (and I'm interested too), but I would generallly prefer gui methods if possible.

> I see almost everywhere wine 6+ is mentioned

Not everybody wants to update a number just because a newversion is available. Itried to stay rather vague about the version you want to use because of that.

Well, Rocksmith works fine since at least Proton 4. I currently use Proton 7.

**Comment by theNizo** [comment]
Closing, because no more interaction
